image: node:21.5.0

pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@16.2.0
    - npm install
    - ng build --output-path public
  artifacts:
    paths:
      - public
  only:
    - main
    - pages
